name: todo_with_resfulapi
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Firebase
  firebase_core: ^2.20.0
  firebase_auth: ^4.8.0
  image_picker: ^0.8.7+5
  google_sign_in: ^6.1.0

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Network
  http: ^1.1.0
  connectivity_plus: ^5.0.2

  # JSON Serialization
  json_annotation: ^4.9.0

  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - images/
